import React, { useState, useEffect, useCallback } from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, Alert, Platform, Share } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { useDatabase } from '@/context/DatabaseContext';
import { useApp } from '@/context/AppContext';
import { useColors } from '@/hooks/useColors';
import { ScreenHeader } from '@/components/ui/ScreenHeader';
import { Badge } from '@/components/ui/Badge';
import { Sale, SaleItem } from '@/types';
import { formatCurrencyFull, formatDate, formatTime } from '@/utils/format';

export default function InvoiceScreen() {
  const colors = useColors();
  const insets = useSafeAreaInsets();
  const { id } = useLocalSearchParams<{ id: string }>();
  const { sales, getSaleItems } = useDatabase();
  const { settings } = useApp();
  const sym = settings.currency_symbol;

  const sale = sales.find(s => s.id === id);
  const [items, setItems] = useState<SaleItem[]>([]);

  useEffect(() => {
    if (id) getSaleItems(id).then(setItems);
  }, [id, getSaleItems]);

  const generateHtml = useCallback(() => {
    const rows = items.map(i => `
      <tr>
        <td>${i.product_name}</td>
        <td style="text-align:center">${i.quantity} ${i.unit || ''}</td>
        <td style="text-align:right">${sym}${i.price.toFixed(2)}</td>
        <td style="text-align:right">${sym}${(i.price * i.quantity).toFixed(2)}</td>
      </tr>`).join('');
    return `<!DOCTYPE html><html><head><meta charset="utf-8"><style>
      body{font-family:sans-serif;padding:24px;color:#1a1a1a;max-width:600px;margin:0 auto}
      h1{color:#1B4F8A;margin-bottom:4px}
      .meta{color:#666;margin-bottom:24px}
      .cust{background:#f0f5ff;padding:12px;border-radius:8px;margin-bottom:20px}
      table{width:100%;border-collapse:collapse;margin-bottom:16px}
      th{background:#1B4F8A;color:#fff;padding:10px;text-align:left;font-size:13px}
      td{padding:10px;border-bottom:1px solid #eee;font-size:14px}
      .total-row{font-weight:bold;font-size:16px;color:#1B4F8A}
      .pay{display:flex;gap:8px;flex-wrap:wrap;margin-top:16px}
      .pill{background:#e8f5e9;color:#2e7d32;padding:6px 14px;border-radius:20px;font-size:13px;font-weight:600}
      .footer{text-align:center;color:#999;font-size:12px;margin-top:32px;border-top:1px solid #eee;padding-top:16px}
    </style></head><body>
      <h1>${settings.business_name}</h1>
      <div class="meta">${settings.business_address ? settings.business_address + '<br>' : ''}${settings.business_phone ? '📞 ' + settings.business_phone : ''}</div>
      <h3>Invoice: ${sale?.invoice_number ?? ''}</h3>
      <p>Date: ${formatDate(sale?.date ?? 0)} at ${formatTime(sale?.date ?? 0)}</p>
      ${sale?.customer_name ? `<div class="cust"><strong>${sale.customer_name}</strong></div>` : ''}
      <table>
        <thead><tr><th>Item</th><th>Qty</th><th>Rate</th><th>Amount</th></tr></thead>
        <tbody>${rows}</tbody>
      </table>
      <table>
        ${sale && sale.discount > 0 ? `<tr><td>Subtotal</td><td style="text-align:right">${sym}${sale.subtotal.toFixed(2)}</td></tr><tr><td>Discount</td><td style="text-align:right">- ${sym}${sale.discount.toFixed(2)}</td></tr>` : ''}
        <tr class="total-row"><td>Total</td><td style="text-align:right">${sym}${sale?.total.toFixed(2)}</td></tr>
      </table>
      ${settings.upi_id ? `<p>UPI: <strong>${settings.upi_id}</strong></p>` : ''}
      <div class="footer">Thank you for your business!<br>Generated by Dukaan Manager</div>
    </body></html>`;
  }, [items, sale, settings, sym]);

  const handleShare = async () => {
    if (Platform.OS === 'web') {
      Alert.alert('Not supported', 'PDF sharing is not available on web');
      return;
    }
    try {
      const PrintModule = await import('expo-print');
      const SharingModule = await import('expo-sharing');
      const { uri } = await PrintModule.printToFileAsync({ html: generateHtml() });
      if (await SharingModule.isAvailableAsync()) {
        await SharingModule.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
      } else {
        Alert.alert('Sharing not available');
      }
    } catch (e) {
      Alert.alert('Error', 'Could not generate PDF');
    }
  };

  const handlePrint = async () => {
    if (Platform.OS === 'web') { Alert.alert('Not supported'); return; }
    try {
      const PrintModule = await import('expo-print');
      await PrintModule.printAsync({ html: generateHtml() });
    } catch (e) {
      Alert.alert('Error', 'Could not print invoice');
    }
  };

  if (!sale) {
    return (
      <View style={[styles.root, { backgroundColor: colors.background }]}>
        <ScreenHeader title="Invoice" onBack={() => router.back()} />
        <View style={styles.center}><Text style={{ color: colors.mutedForeground }}>Invoice not found</Text></View>
      </View>
    );
  }

  const botPad = Platform.OS === 'web' ? 34 : insets.bottom + 10;

  return (
    <View style={[styles.root, { backgroundColor: colors.background }]}>
      <ScreenHeader title={sale.invoice_number} onBack={() => router.back()} rightIcon={Platform.OS !== 'web' ? 'share-outline' : undefined} onRightPress={Platform.OS !== 'web' ? handleShare : undefined} />

      <ScrollView contentContainerStyle={[styles.scroll, { paddingBottom: botPad + 20 }]}>
        {/* Business Header */}
        <View style={[styles.bizHeader, { backgroundColor: colors.headerBackground }]}>
          <Text style={styles.bizName}>{settings.business_name}</Text>
          {settings.business_address ? <Text style={styles.bizSub}>{settings.business_address}</Text> : null}
          {settings.business_phone ? <Text style={styles.bizSub}>📞 {settings.business_phone}</Text> : null}
        </View>

        {/* Invoice Meta */}
        <View style={[styles.meta, { backgroundColor: colors.card, borderColor: colors.border }]}>
          <View style={styles.metaRow}>
            <Text style={[styles.metaLabel, { color: colors.mutedForeground }]}>Invoice #</Text>
            <Text style={[styles.metaValue, { color: colors.primary }]}>{sale.invoice_number}</Text>
          </View>
          <View style={styles.metaRow}>
            <Text style={[styles.metaLabel, { color: colors.mutedForeground }]}>Date</Text>
            <Text style={[styles.metaValue, { color: colors.foreground }]}>{formatDate(sale.date)}</Text>
          </View>
          <View style={styles.metaRow}>
            <Text style={[styles.metaLabel, { color: colors.mutedForeground }]}>Time</Text>
            <Text style={[styles.metaValue, { color: colors.foreground }]}>{formatTime(sale.date)}</Text>
          </View>
          {sale.customer_name ? (
            <View style={styles.metaRow}>
              <Text style={[styles.metaLabel, { color: colors.mutedForeground }]}>Customer</Text>
              <Text style={[styles.metaValue, { color: colors.foreground }]}>{sale.customer_name}</Text>
            </View>
          ) : null}
          <View style={styles.metaRow}>
            <Text style={[styles.metaLabel, { color: colors.mutedForeground }]}>Payment</Text>
            <Badge label={sale.payment_method.toUpperCase()} variant={sale.payment_method === 'cash' ? 'success' : sale.payment_method === 'upi' ? 'primary' : 'credit'} />
          </View>
        </View>

        {/* Items Table */}
        <Text style={[styles.sec, { color: colors.mutedForeground }]}>ITEMS</Text>
        <View style={[styles.table, { backgroundColor: colors.card, borderColor: colors.border }]}>
          <View style={[styles.tableHdr, { backgroundColor: colors.secondary }]}>
            <Text style={[styles.thItem, { color: colors.primary }]}>Item</Text>
            <Text style={[styles.thQty, { color: colors.primary }]}>Qty</Text>
            <Text style={[styles.thAmt, { color: colors.primary }]}>Rate</Text>
            <Text style={[styles.thAmt, { color: colors.primary }]}>Total</Text>
          </View>
          {items.map((item, idx) => (
            <View key={idx} style={[styles.tableRow, { borderTopColor: colors.border }]}>
              <Text style={[styles.tdItem, { color: colors.foreground }]} numberOfLines={2}>{item.product_name}</Text>
              <Text style={[styles.tdQty, { color: colors.mutedForeground }]}>{item.quantity}{item.unit ? ' ' + item.unit : ''}</Text>
              <Text style={[styles.tdAmt, { color: colors.mutedForeground }]}>{sym}{item.price.toFixed(2)}</Text>
              <Text style={[styles.tdAmt, { color: colors.foreground }]}>{sym}{(item.price * item.quantity).toFixed(2)}</Text>
            </View>
          ))}
        </View>

        {/* Totals */}
        <View style={[styles.totals, { backgroundColor: colors.card, borderColor: colors.border }]}>
          {sale.discount > 0 && (
            <>
              <View style={styles.totalRow}>
                <Text style={[styles.tlLabel, { color: colors.mutedForeground }]}>Subtotal</Text>
                <Text style={[styles.tlValue, { color: colors.foreground }]}>{formatCurrencyFull(sale.subtotal, sym)}</Text>
              </View>
              <View style={styles.totalRow}>
                <Text style={[styles.tlLabel, { color: colors.expense }]}>Discount</Text>
                <Text style={[styles.tlValue, { color: colors.expense }]}>- {formatCurrencyFull(sale.discount, sym)}</Text>
              </View>
              <View style={[styles.divider, { backgroundColor: colors.border }]} />
            </>
          )}
          {sale.cash_amount > 0 && <View style={styles.totalRow}><Text style={[styles.tlLabel, { color: colors.mutedForeground }]}>Cash</Text><Text style={[styles.tlValue, { color: colors.success }]}>{formatCurrencyFull(sale.cash_amount, sym)}</Text></View>}
          {sale.upi_amount > 0 && <View style={styles.totalRow}><Text style={[styles.tlLabel, { color: colors.mutedForeground }]}>UPI</Text><Text style={[styles.tlValue, { color: colors.primary }]}>{formatCurrencyFull(sale.upi_amount, sym)}</Text></View>}
          {sale.credit_amount > 0 && <View style={styles.totalRow}><Text style={[styles.tlLabel, { color: colors.credit }]}>Credit</Text><Text style={[styles.tlValue, { color: colors.credit }]}>{formatCurrencyFull(sale.credit_amount, sym)}</Text></View>}
          <View style={[styles.divider, { backgroundColor: colors.border }]} />
          <View style={styles.totalRow}>
            <Text style={[styles.grandLbl, { color: colors.foreground }]}>Total</Text>
            <Text style={[styles.grandAmt, { color: colors.primary }]}>{formatCurrencyFull(sale.total, sym)}</Text>
          </View>
        </View>

        {settings.upi_id ? (
          <View style={[styles.upiBox, { backgroundColor: colors.successLight, borderColor: colors.success }]}>
            <Ionicons name="phone-portrait-outline" size={18} color={colors.success} />
            <Text style={[styles.upiText, { color: colors.success }]}>Pay via UPI: <Text style={{ fontFamily: 'Inter_700Bold' }}>{settings.upi_id}</Text></Text>
          </View>
        ) : null}

        {sale.notes ? (
          <View style={[styles.notesBox, { backgroundColor: colors.muted, borderColor: colors.border }]}>
            <Text style={[styles.notesText, { color: colors.mutedForeground }]}>📝 {sale.notes}</Text>
          </View>
        ) : null}

        {/* Action Buttons */}
        {Platform.OS !== 'web' && (
          <View style={styles.btnRow}>
            <TouchableOpacity style={[styles.actionBtn, { backgroundColor: colors.secondary, borderColor: colors.primary }]} onPress={handleShare}>
              <Ionicons name="share-outline" size={20} color={colors.primary} />
              <Text style={[styles.actionBtnText, { color: colors.primary }]}>Share PDF</Text>
            </TouchableOpacity>
            <TouchableOpacity style={[styles.actionBtn, { backgroundColor: colors.muted, borderColor: colors.border }]} onPress={handlePrint}>
              <Ionicons name="print-outline" size={20} color={colors.foreground} />
              <Text style={[styles.actionBtnText, { color: colors.foreground }]}>Print</Text>
            </TouchableOpacity>
          </View>
        )}

        <TouchableOpacity style={[styles.newBillBtn, { backgroundColor: colors.primary }]} onPress={() => router.replace('/billing/new')}>
          <Ionicons name="add" size={20} color="#fff" />
          <Text style={styles.newBillText}>New Bill</Text>
        </TouchableOpacity>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  root: { flex: 1 },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  scroll: { padding: 16 },
  bizHeader: { borderRadius: 14, padding: 16, marginBottom: 12, alignItems: 'center' },
  bizName: { fontSize: 20, fontFamily: 'Inter_700Bold', color: '#fff', textAlign: 'center' },
  bizSub: { fontSize: 13, fontFamily: 'Inter_400Regular', color: 'rgba(255,255,255,0.8)', marginTop: 4, textAlign: 'center' },
  meta: { borderRadius: 14, borderWidth: 1, padding: 14, gap: 10, marginBottom: 12 },
  metaRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  metaLabel: { fontSize: 13, fontFamily: 'Inter_400Regular' },
  metaValue: { fontSize: 13, fontFamily: 'Inter_600SemiBold' },
  sec: { fontSize: 11, fontFamily: 'Inter_600SemiBold', letterSpacing: 0.8, marginBottom: 8, marginTop: 4 },
  table: { borderRadius: 12, borderWidth: 1, overflow: 'hidden', marginBottom: 12 },
  tableHdr: { flexDirection: 'row', padding: 10, gap: 4 },
  thItem: { flex: 3, fontSize: 12, fontFamily: 'Inter_600SemiBold' },
  thQty: { flex: 1, fontSize: 12, fontFamily: 'Inter_600SemiBold', textAlign: 'center' },
  thAmt: { flex: 1.5, fontSize: 12, fontFamily: 'Inter_600SemiBold', textAlign: 'right' },
  tableRow: { flexDirection: 'row', padding: 10, borderTopWidth: 1, gap: 4 },
  tdItem: { flex: 3, fontSize: 13, fontFamily: 'Inter_400Regular' },
  tdQty: { flex: 1, fontSize: 13, fontFamily: 'Inter_400Regular', textAlign: 'center' },
  tdAmt: { flex: 1.5, fontSize: 13, fontFamily: 'Inter_400Regular', textAlign: 'right' },
  totals: { borderRadius: 12, borderWidth: 1, padding: 14, gap: 10, marginBottom: 12 },
  totalRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  tlLabel: { fontSize: 14, fontFamily: 'Inter_400Regular' },
  tlValue: { fontSize: 14, fontFamily: 'Inter_500Medium' },
  divider: { height: 1 },
  grandLbl: { fontSize: 16, fontFamily: 'Inter_700Bold' },
  grandAmt: { fontSize: 22, fontFamily: 'Inter_700Bold' },
  upiBox: { flexDirection: 'row', alignItems: 'center', gap: 8, padding: 12, borderRadius: 10, borderWidth: 1, marginBottom: 8 },
  upiText: { fontSize: 13, fontFamily: 'Inter_400Regular' },
  notesBox: { padding: 12, borderRadius: 10, borderWidth: 1, marginBottom: 8 },
  notesText: { fontSize: 13, fontFamily: 'Inter_400Regular' },
  btnRow: { flexDirection: 'row', gap: 10, marginBottom: 12 },
  actionBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, padding: 14, borderRadius: 12, borderWidth: 1.5 },
  actionBtnText: { fontSize: 14, fontFamily: 'Inter_600SemiBold' },
  newBillBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, padding: 16, borderRadius: 14, marginTop: 8 },
  newBillText: { fontSize: 16, fontFamily: 'Inter_700Bold', color: '#fff' },
});
