import React,{useState} from 'react';
import {View,Text,StyleSheet,TextInput,TouchableOpacity,ScrollView,Alert,Platform,KeyboardAvoidingView,Image} from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import {useSafeAreaInsets} from 'react-native-safe-area-context';import {router,useLocalSearchParams} from 'expo-router';import {useDatabase} from '@/context/DatabaseContext';import {useColors} from '@/hooks/useColors';import {ScreenHeader} from '@/components/ui/ScreenHeader';import {Ionicons} from '@expo/vector-icons';
export default function AddCustomerScreen(){const colors=useColors(),insets=useSafeAreaInsets(),{id}=useLocalSearchParams<{id?:string}>(),{customers,addCustomer,updateCustomer}=useDatabase();const existing=id?customers.find(c=>c.id===id):null,isEdit=!!existing;const[name,setName]=useState(existing?.name??''),[mobile,setMobile]=useState(existing?.mobile??''),[photo,setPhoto]=useState(existing?.photo_uri??''),[address,setAddress]=useState(existing?.address??''),[notes,setNotes]=useState(existing?.notes??''),[saving,setSaving]=useState(false);
 const pickPhoto=async(camera=false)=>{try{if(camera){const p=await ImagePicker.requestCameraPermissionsAsync();if(!p.granted){Alert.alert('Camera permission','Allow camera permission to take customer photo.');return}}else{const p=await ImagePicker.requestMediaLibraryPermissionsAsync();if(!p.granted){Alert.alert('Photo permission','Allow photo permission to choose a customer photo.');return}}const r=camera?await ImagePicker.launchCameraAsync({mediaTypes:['images'],allowsEditing:true,aspect:[1,1],quality:.75}):await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],allowsEditing:true,aspect:[1,1],quality:.75});if(!r.canceled&&r.assets[0]?.uri)setPhoto(r.assets[0].uri)}catch{Alert.alert('Photo error','Could not open camera/gallery.')}};
 const handleSave=async()=>{if(!name.trim()){Alert.alert('Name required','Please enter customer full name.');return}const phone=mobile.replace(/\D/g,'');if(phone&&phone.length!==10){Alert.alert('Mobile number','Please enter a valid 10-digit mobile number.');return}setSaving(true);try{const data={name:name.trim(),mobile:phone,address:address.trim(),notes:notes.trim(),photo_uri:photo};if(isEdit&&existing)await updateCustomer(existing.id,data);else await addCustomer(data);router.back()}catch(e){Alert.alert('Error',e instanceof Error?e.message:'Failed to save customer')}finally{setSaving(false)}};
 const botPad=Platform.OS==='web'?34:insets.bottom+10;return <View style={[styles.root,{backgroundColor:colors.background}]}><ScreenHeader title={isEdit?'Edit Customer':'Add Customer'} onBack={()=>router.back()}/><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':'height'} keyboardVerticalOffset={Platform.OS==='ios'?8:0}><ScrollView contentContainerStyle={[styles.scroll,{paddingBottom:botPad+20}]} keyboardShouldPersistTaps="handled" automaticallyAdjustKeyboardInsets contentInsetAdjustmentBehavior="automatic">
  <View style={styles.photoSection}><TouchableOpacity onPress={()=>pickPhoto(false)} activeOpacity={.8} style={[styles.photo,{backgroundColor:colors.muted,borderColor:colors.border}]}>{photo?<Image source={{uri:photo}} style={styles.photoImg}/>:<Ionicons name="person" size={44} color={colors.mutedForeground}/>}</TouchableOpacity><Text style={[styles.photoTitle,{color:colors.foreground}]}>{photo?'Customer Photo':'Photo lo / lagao'}</Text><Text style={[styles.photoHint,{color:colors.mutedForeground}]}>Photo lene ke liye Camera, purani photo ke liye Gallery</Text><View style={styles.photoBtns}><TouchableOpacity style={[styles.photoBtn,{borderColor:colors.border,backgroundColor:colors.card}]} onPress={()=>pickPhoto(true)}><Ionicons name="camera-outline" size={20} color={colors.primary}/><Text style={[styles.photoBtnText,{color:colors.foreground}]}>Camera</Text></TouchableOpacity><TouchableOpacity style={[styles.photoBtn,{borderColor:colors.border,backgroundColor:colors.card}]} onPress={()=>pickPhoto(false)}><Ionicons name="images-outline" size={20} color={colors.primary}/><Text style={[styles.photoBtnText,{color:colors.foreground}]}>Gallery</Text></TouchableOpacity>{photo?<TouchableOpacity style={[styles.removeBtn,{backgroundColor:colors.muted}]} onPress={()=>setPhoto('')}><Ionicons name="trash-outline" size={19} color={colors.destructive}/></TouchableOpacity>:null}</View></View>
  <View style={styles.field}><Text style={[styles.label,{color:colors.mutedForeground}]}>Customer Name *</Text><TextInput style={[styles.input,{color:colors.foreground,borderColor:colors.border,backgroundColor:colors.card}]} value={name} onChangeText={setName} placeholder="Papa / Dada ko customer ka naam likho" placeholderTextColor={colors.mutedForeground} keyboardType="default" autoCapitalize="words" /></View>
  <View style={styles.field}><Text style={[styles.label,{color:colors.mutedForeground}]}>Mobile Number</Text><TextInput style={[styles.input,{color:colors.foreground,borderColor:colors.border,backgroundColor:colors.card}]} value={mobile} onChangeText={setMobile} placeholder="Mobile number (optional)" placeholderTextColor={colors.mutedForeground} keyboardType="phone-pad" /></View>
  <View style={styles.field}><Text style={[styles.label,{color:colors.mutedForeground}]}>Gaon Ka Naam</Text><TextInput style={[styles.input,{color:colors.foreground,borderColor:colors.border,backgroundColor:colors.card}]} value={address} onChangeText={setAddress} placeholder="Gaon ka naam likho" placeholderTextColor={colors.mutedForeground} keyboardType="default" /></View>
  <View style={styles.field}><Text style={[styles.label,{color:colors.mutedForeground}]}>Notes</Text><TextInput style={[styles.input,styles.notesInput,{color:colors.foreground,borderColor:colors.border,backgroundColor:colors.card}]} value={notes} onChangeText={setNotes} placeholder="Koi extra baat likho" placeholderTextColor={colors.mutedForeground} keyboardType="default" multiline /></View>
  <TouchableOpacity style={[styles.save,{backgroundColor:saving?colors.muted:colors.primary}]} onPress={handleSave} disabled={saving}><Ionicons name="checkmark-circle-outline" size={21} color="#fff"/><Text style={styles.saveText}>{saving?'Saving...':isEdit?'Update Customer':'Save Customer'}</Text></TouchableOpacity>
 </ScrollView></KeyboardAvoidingView></View>}
const styles=StyleSheet.create({root:{flex:1},scroll:{padding:20},photoSection:{alignItems:'center',marginBottom:22},photo:{width:104,height:104,borderRadius:52,borderWidth:1.5,alignItems:'center',justifyContent:'center',overflow:'hidden'},photoImg:{width:'100%',height:'100%'},photoTitle:{fontSize:16,fontFamily:'Inter_700Bold',marginTop:10},photoHint:{fontSize:12,fontFamily:'Inter_400Regular',marginTop:3},photoBtns:{flexDirection:'row',gap:8,marginTop:12},photoBtn:{flexDirection:'row',alignItems:'center',gap:6,borderWidth:1,borderRadius:10,paddingHorizontal:13,paddingVertical:9},photoBtnText:{fontSize:13,fontFamily:'Inter_600SemiBold'},removeBtn:{width:40,height:40,borderRadius:10,alignItems:'center',justifyContent:'center'},field:{marginBottom:16},label:{fontSize:13,fontFamily:'Inter_500Medium',marginBottom:6},input:{borderWidth:1,borderRadius:12,padding:14,fontSize:15,fontFamily:'Inter_400Regular',minHeight:54},notesInput:{minHeight:84,textAlignVertical:'top'},save:{padding:16,borderRadius:14,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:7,marginTop:6},saveText:{fontSize:16,fontFamily:'Inter_700Bold',color:'#fff'}});
